#differernt profile , made for development only
#this yaml is for development phase we use different properties like db and all other stuffs like port number etc.
spring:

  data:
    mongodb:
      uri: mongodb+srv://uselessacc3112_db_user:LmZkm2hkgsj1GJco@cluster0.lixzv0a.mongodb.net/journaldb?retryWrites=true&w=majority&appName=Cluster0
      database: journaldb
      auto-index-creation : true

server:
  port : 8081
  servlet:
    context-path: /development







